### ISSUE TITLE
初始化开始java报错连接127.0.0.1:8081失败

### ISSUE THREAD

**Issue by Allan9977** [nelivacn/FAT-selfTest#2]
报错版本:  4a963297a633cd9e0688456d704ec5dd9970d407

[文档](https://github.com/nelivacn/FAT-selfTest/blob/main/README.md)中开始自助测试之前的所有步骤均正常完成，T4双卡容器内部查看显卡均正常

进行自助测试步骤：
1. 进入测试页面[http://ip:8040/self/test](http://127.0.0.1:8040/self/test)
2. 输入镜像名称与程序包所在绝对路径
3. 点击初始化按钮并观察测试日志输出
    * 网页端显示`开始初始化，请稍等`
    * 去宿主后台查看docker，自动成功创建了selftest-xxxxxxxxxx容器
    * out.log中报错信息如下
```
2024-05-13 15:58:22.580  INFO 86230 --- [           main] com.liandun.self.Application             : Starting Application v1.0.0 using Java 1.8.0_412 on xxxxxxxxx with PID 86230 (/workspace/script/selftest/self_test-1.0.0.jar started by root in /workspace/script/selftest)
2024-05-13 15:58:22.582 DEBUG 86230 --- [           main] com.liandun.self.Application             : Running with Spring Boot v2.7.15, Spring v5.3.29
2024-05-13 15:58:22.582  INFO 86230 --- [           main] com.liandun.self.Application             : No active profile set, falling back to 1 default profile: "default"
2024-05-13 15:58:23.333  INFO 86230 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8040 (http)
2024-05-13 15:58:23.340  INFO 86230 --- [           main] o.a.coyote.http11.Http11NioProtocol      : Initializing ProtocolHandler ["http-nio-8040"]
2024-05-13 15:58:23.341  INFO 86230 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-05-13 15:58:23.341  INFO 86230 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.79]
2024-05-13 15:58:23.394  INFO 86230 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-05-13 15:58:23.394  INFO 86230 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 779 ms
2024-05-13 15:58:24.219  INFO 86230 --- [           main] o.a.coyote.http11.Http11NioProtocol      : Starting ProtocolHandler ["http-nio-8040"]
2024-05-13 15:58:24.231  INFO 86230 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8040 (http) with context path ''
2024-05-13 15:58:24.233  INFO 86230 --- [           main] o.s.m.s.b.SimpleBrokerMessageHandler     : Starting...
2024-05-13 15:58:24.233  INFO 86230 --- [           main] o.s.m.s.b.SimpleBrokerMessageHandler     : BrokerAvailabilityEvent[available=true, SimpleBrokerMessageHandler [org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry@2525ff7e]]
2024-05-13 15:58:24.233  INFO 86230 --- [           main] o.s.m.s.b.SimpleBrokerMessageHandler     : Started.
2024-05-13 15:58:24.240  INFO 86230 --- [           main] com.liandun.self.Application             : Started Application in 1.995 seconds (JVM running for 2.466)
2024-05-13 15:58:40.761  INFO 86230 --- [nio-8040-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-05-13 15:58:40.761  INFO 86230 --- [nio-8040-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-05-13 15:58:40.762  INFO 86230 --- [nio-8040-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2024-05-13 15:58:40.817  INFO 86230 --- [nio-8040-exec-1] c.l.s.s.impl.SelfResultServiceImpl       : existCon ======= false
2024-05-13 15:58:40.818  INFO 86230 --- [nio-8040-exec-1] c.l.s.s.impl.SelfResultServiceImpl       : 文件删除成功：1n1_xxxxxxxxxxxxxxxxxxxxxxxxxxx.tar.st
2024-05-13 15:58:40.818  INFO 86230 --- [nio-8040-exec-1] c.l.s.s.impl.SelfResultServiceImpl       : 新文件创建成功：1n1_xxxxxxxxxxxxxxxxxxxxxxxxxxx.tar.st
2024-05-13 15:58:45.559  INFO 86230 --- [nio-8040-exec-1] c.l.s.s.impl.SelfResultServiceImpl       : containerId：f72c7bf4a6xxxxxxxxxxxxxxxxx
java.net.ConnectException: Failed to connect to /127.0.0.1:8081
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at com.liandun.self.util.OkHttpUtil.get(OkHttpUtil.java:63)
	at com.liandun.self.service.impl.SelfResultServiceImpl.testDecompress(SelfResultServiceImpl.java:258)
	at com.liandun.self.service.impl.SelfResultServiceImpl.startContainer(SelfResultServiceImpl.java:191)
	at com.liandun.self.service.impl.SelfResultServiceImpl.createContainer(SelfResultServiceImpl.java:149)
	at com.liandun.self.rest.SelfResultController.startSelfTest(SelfResultController.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	... 73 more
java.lang.RuntimeException: http请求失败
	at com.liandun.self.service.impl.SelfResultServiceImpl.testCheckDir(SelfResultServiceImpl.java:323)
	at com.liandun.self.service.impl.SelfResultServiceImpl.testDecompress(SelfResultServiceImpl.java:290)
	at com.liandun.self.service.impl.SelfResultServiceImpl.startContainer(SelfResultServiceImpl.java:191)
	at com.liandun.self.service.impl.SelfResultServiceImpl.createContainer(SelfResultServiceImpl.java:149)
	at com.liandun.self.rest.SelfResultController.startSelfTest(SelfResultController.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
2024-05-13 15:59:23.994  INFO 86230 --- [essageBroker-11] o.s.w.s.c.WebSocketMessageBrokerStats    : WebSocketSession[1 current WS(1)-HttpStream(0)-HttpPoll(0), 1 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(1)-CONNECTED(1)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 6, active threads = 0, queued tasks = 0, completed tasks = 6], outboundChannel[pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 3], sockJsScheduler[pool size = 36, active threads = 1, queued tasks = 2, completed tasks = 30]
2024-05-13 16:00:11.429 ERROR 86230 --- [nio-8040-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
```

**Comment by msbrm** [comment]
out.log 同级目录下是否有 OUT 日志文件，检查该文件内容

**Comment by Allan9977** [comment]
> out.log 同级目录下是否有 OUT 日志文件，检查该文件内容

感谢答复，该问题已解决，为宿主、docker使用的java版本不适配系统


## 进行到第三步无任何反应

目前流程可正常进行到授权，但是到第三步， 点击'功能测试'按钮后（不论填不填测试轮数），网页界面均无任何反应， 各log也无任何反馈， 请问该现象是否正常？

* 网页端信息
```
2024-05-14 11:48:35:授权文件上传成功
2024-05-14 11:48:35:授权成功
2024-05-14 11:48:36:正在关闭容器
2024-05-14 11:48:56:容器关闭成功
2024-05-14 11:48:56:初始化完成
2024-05-14 11:48:56:初始化完成，请点击功能测试按钮开始测试
```
* out.log
```
2024-05-14 11:48:35.948  INFO 79284 --- [nio-8040-exec-5] c.l.s.s.impl.SelfResultServiceImpl       : AUTH_OK:授权成功
2024-05-14 11:48:36.053  INFO 79284 --- [nio-8040-exec-5] c.l.s.s.impl.SelfResultServiceImpl       : SHUTDOWN:授权结束
2024-05-14 11:48:46.481  INFO 79284 --- [nio-8040-exec-5] c.l.s.s.impl.SelfResultServiceImpl       : stopContainerAsync cost time: 10425 ms
```
* OUT
```
Writer sent: AUTH_OK:授权成功
Writer sent: SHUTDOWN:授权结束
```
* docker 状态
```
CONTAINER ID   IMAGE                                             COMMAND                  CREATED          STATUS                        PORTS                                       NAMES
93cf3fff3be2   nelivacn/fat:cuda12.2.2-centos7-selftestV2024.1   "/sbin/init"             12 minutes ago   Exited (137) 11 minutes ago                                               selftest-1715658447866
```
* 宿主后台pid状态
```
./selfTest.sh status
self_test is running. pid=79284.

ps -p 79284
   PID TTY          TIME CMD
 79284 pts/1    00:00:26 java
```

**Comment by msbrm** [comment]
点击'功能测试'按钮后（不论填不填测试轮数），网页界面均无任何反应
使用的什么浏览器 我们这边排查一下

**Comment by Allan9977** [comment]
> 点击'功能测试'按钮后（不论填不填测试轮数），网页界面均无任何反应 使用的什么浏览器 我们这边排查一下

Firefox 125.0.3   其他也试了chrome、edge游览器，均为上述同一个现象。 out.log中自授权结束、停止docker后，点击‘功能测试’，再无新的log条目产生， 容器也是处于退出状态

```
2024-05-17 20:13:58.152  INFO 113348 --- [nio-8040-exec-6] c.l.s.s.impl.SelfResultServiceImpl       : AUTH_OK:授权成功
2024-05-17 20:13:58.257  INFO 113348 --- [nio-8040-exec-6] c.l.s.s.impl.SelfResultServiceImpl       : SHUTDOWN:授权结束
2024-05-17 20:14:08.401  INFO 113348 --- [nio-8040-exec-6] c.l.s.s.impl.SelfResultServiceImpl       : stopContainerAsync cost time: 10141 ms
```

**Comment by Allan9977** [comment]
> 点击'功能测试'按钮后（不论填不填测试轮数），网页界面均无任何反应 使用的什么浏览器 我们这边排查一下

Firefox 125.0.3   其他也试了chrome、edge游览器，均为上述同一个现象。 out.log中自授权结束、停止docker后，点击‘功能测试’，再无新的log条目产生， 容器也是处于退出状态

```
2024-05-17 20:13:58.152  INFO 113348 --- [nio-8040-exec-6] c.l.s.s.impl.SelfResultServiceImpl       : AUTH_OK:授权成功
2024-05-17 20:13:58.257  INFO 113348 --- [nio-8040-exec-6] c.l.s.s.impl.SelfResultServiceImpl       : SHUTDOWN:授权结束
2024-05-17 20:14:08.401  INFO 113348 --- [nio-8040-exec-6] c.l.s.s.impl.SelfResultServiceImpl       : stopContainerAsync cost time: 10141 ms
```

**Comment by msbrm** [comment]
浏览器适配的问题 已修正
