### ISSUE TITLE
初始化成功后，执行第三步功能测试，java报错连接127.0.0.1:8081失败

### ISSUE THREAD

**Issue by Aqdjuly** [nelivacn/FAT-selfTest#6]
初始化已成功，页面点击 第三步，执行功能验证
![image](https://github.com/nelivacn/FAT-selfTest/assets/171911600/451e6424-008c-4e63-9356-3f6dd3b73faa)

out.log 中报错如下：
`2024-06-20 10:01:35.540  INFO 3743295 --- [nio-8040-exec-8] c.l.s.s.impl.SelfResultServiceImpl       : AUTH_OK:环境脚本成功
2024-06-20 10:01:35.723  INFO 3743295 --- [nio-8040-exec-8] c.l.s.s.impl.SelfResultServiceImpl       : SHUTDOWN:环境设置执行结束
2024-06-20 10:01:35.723  INFO 3743295 --- [nio-8040-exec-8] c.l.s.s.impl.SelfResultServiceImpl       : 环境配置结束
2024-06-20 10:01:41.300  INFO 3743295 --- [essageBroker-20] o.s.w.s.c.WebSocketMessageBrokerStats    : WebSocketSession[3 current WS(3)-HttpStream(0)-HttpPoll(0), 3 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(3)-CONNECTED(3)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 18, active threads = 0, queued tasks = 0, completed tasks = 18], outboundChannel[pool size = 39, active threads = 0, queued tasks = 0, completed tasks = 39], sockJsScheduler[pool size = 64, active threads = 1, queued tasks = 4, completed tasks = 77]
2024-06-20 10:02:26.446  INFO 3743295 --- [nio-8040-exec-8] c.l.s.s.impl.SelfResultServiceImpl       : 指纹文件结束
java.net.ConnectException: Failed to connect to /127.0.0.1:8081
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at com.liandun.self.util.OkHttpUtil.get(OkHttpUtil.java:63)
        at com.liandun.self.service.impl.ExecDockerTask.restartEnv(ExecDockerTask.java:117)
        at com.liandun.self.service.impl.ExecDockerTask.cycleTest(ExecDockerTask.java:90)
        at com.liandun.self.service.impl.ExecDockerTask$$FastClassBySpringCGLIB$$1a2d4591.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
        ... 31 more
2024-06-20 10:02:43.429 ERROR 3743295 --- [impleExecutor-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.liandun.self.service.impl.ExecDockerTask.cycleTest(java.lang.String)

com.github.dockerjava.api.exception.NotModifiedException: Status 304:
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:235)
        at com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
        at com.github.dockerjava.core.exec.StopContainerCmdExec.execute(StopContainerCmdExec.java:33)
        at com.github.dockerjava.core.exec.StopContainerCmdExec.execute(StopContainerCmdExec.java:13)
        at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
        at com.github.dockerjava.core.command.StopContainerCmdImpl.exec(StopContainerCmdImpl.java:63)
        at com.zd.dockerceping.service.CepingDockerUtils.stopContainer(CepingDockerUtils.java:156)
        at com.liandun.self.service.impl.ExecDockerTask.cycleTest(ExecDockerTask.java:100)
        at com.liandun.self.service.impl.ExecDockerTask$$FastClassBySpringCGLIB$$1a2d4591.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`
OUT文件中内容为
![image](https://github.com/nelivacn/FAT-selfTest/assets/171911600/cab7332d-8c34-46ff-92b6-4806a40fb4aa)

./selfTest.sh status
`self_test is running. pid=3743295.`

ps -ef|grep 3743295
`root     3743295       1  1 10:00 pts/1    00:00:33 ./jre//bin/java -Xms200m -Xmx500m -XX:MetaspaceSize=150m -Dmyname=self_test -Duser.timezone=Asia/Shanghai -Dfile.encoding=utf-8 -jar /workspace/script/selftest/self_test-1.0.0.jar
`

请问需要怎么进一步排查

**Comment by msbrm** [comment]
程序包方便发过来吗 我们测试一下

**Comment by fx34247** [comment]
你好，请问脚本java代码是不是对SelfResultServiceImpl对testGenFingerprint函数中的分支if (response.split(":")[0].equals("AUTH_OK")) 存在STOP_CONTAINER的前提条件:非过车以及非聚类的条件漏加了，导致cycleTest执行的时候，无法正确的执行，直接执行ExecDockerTask类中的restartEnv()函数去了，实际此时并没有可运行的docker
