### ISSUE TITLE
无需授权的聚档/过车存在BUG，初始化成功后，执行第三步功能测试，java报错连接127.0.0.1:8081失败

### ISSUE THREAD

**Issue by fx34247** [nelivacn/FAT-selfTest#7]
报错信息与https://github.com/nelivacn/FAT-selfTest/issues/6报错一致,
out.log中报错如下:
2024-06-25 10:22:46.545  INFO 33298 --- [nio-8040-exec-9] c.l.s.s.impl.SelfResultServiceImpl       : 解压结束
2024-06-25 10:22:46.761  INFO 33298 --- [nio-8040-exec-9] c.l.s.s.impl.SelfResultServiceImpl       : 文件检查结束
2024-06-25 10:23:18.429  INFO 33298 --- [nio-8040-exec-9] c.l.s.s.impl.SelfResultServiceImpl       : INFO_LOG%!%执行 `/workspace/projects/UNVC006.00/tools/env_config.sh` 完毕 ，返回 0
2024-06-25 10:23:18.533  INFO 33298 --- [nio-8040-exec-9] c.l.s.s.impl.SelfResultServiceImpl       : AUTH_OK:环境脚本成功
2024-06-25 10:23:18.639  INFO 33298 --- [nio-8040-exec-9] c.l.s.s.impl.SelfResultServiceImpl       : SHUTDOWN:环境设置执行结束
2024-06-25 10:23:18.639  INFO 33298 --- [nio-8040-exec-9] c.l.s.s.impl.SelfResultServiceImpl       : 环境配置结束
2024-06-25 10:23:47.223  INFO 33298 --- [nio-8040-exec-9] c.l.s.s.impl.SelfResultServiceImpl       : 指纹文件结束
java.net.ConnectException: Failed to connect to /127.0.0.1:8081
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
 
通过解压JAR包: self_test-1.0.0.jar与docker-ceping-web-240417-24.2.2-ALPHA.jar,
确认报错位置是在执行ExecDockerTask中的cycleTest时:
针对if (!StringUtils.startsWith(lastName, "vehicle_") && !StringUtils.startsWith(lastName, "cluster_")) 条件满足时，才会执行启动docker操作: CepingDockerUtils.execCmd(this.dockerClient, containerId, new String[]{this.execCmd0, this.execCmd1});
而cluster直接就执行restartEnv()

实际在初始化阶段:SelfResultServiceImpl类中在函数testGenFingerprint执行环节:
对于无需授权的处理逻辑直接执行CepingDockerUtils.stopContainer(this.dockerClient, DataManager.getContainerId());
对于需要上传授权的，在upload处理上增加了if (!StringUtils.startsWith(lastName, "vehicle_") && !StringUtils.startsWith(lastName, "cluster_"))才 this.execDockerTask.stopContainerAsync(this.dockerClient, containerId);的前提条件

所以还请尽快更新self_test-1.0.0.jar

**Comment by msbrm** [comment]
已经更新了
车辆和聚类验证 不包含稳定性验证
初始化完成后不需要关闭容器
